# Generated by Django 4.2.2 on 2023-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseisjLaw', '0002_chapitre_livre_titre_section_chapitre_titre_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alinea',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livre',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='titre',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
